-- ENTERPRISE SECURITY & IDENTITY (THE FORTRESS)

-- 1. Custom Roles Table (RBAC)
CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role TEXT CHECK (role IN ('user', 'creator', 'moderator', 'admin')) DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, role)
);

-- 2. Audit Logs (For GDPR/Security Compliance)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  action TEXT NOT NULL, -- e.g., 'POST_DELETE', 'USER_LOGIN', 'PERM_CHANGE'
  table_name TEXT,
  record_id TEXT,
  old_data JSONB,
  new_data JSONB,
  ip_address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Functions for RBAC checks
CREATE OR REPLACE FUNCTION public.has_role(required_role TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles 
    WHERE user_id = auth.uid() 
    AND role = required_role
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Advanced RLS Policies for Media (Creator/Moderator Tiers)
-- Creators can view their own private posts
CREATE POLICY "Creators can manage private content" ON public.media
FOR ALL USING (auth.uid() = author_id OR public.has_role('moderator') OR public.has_role('admin'));

-- 1. Only admins can view Audit Logs
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins only access audit logs" ON audit_logs
FOR SELECT USING (public.has_role('admin'));

-- 2. MFA Implementation Tip (UI level)
-- We will add a 'is_mfa_enabled' flag to the profile
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_mfa_enabled BOOLEAN DEFAULT FALSE;

-- 3. Private Storage Signed Access
-- This requires server-side logic in Flutter to fetch signed URLs,
-- which we will implement in the MediaProvider.
