// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:my_circle/providers/enhanced_media_provider.dart';
import 'package:my_circle/repositories/media_repository.dart';
import 'package:my_circle/models/media_item.dart';

@GenerateMocks([
  MediaRepository,
  MediaItem,
])
import 'package:my_circle/test/providers/enhanced_media_provider_test.dart';
