// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:my_circle/providers/enhanced_auth_provider.dart';
import 'package:my_circle/repositories/auth_repository.dart';
import 'package:my_circle/repositories/user_repository.dart';
import 'package:my_circle/models/social_user.dart';

@GenerateMocks([
  AuthRepository,
  UserRepository,
  AuthResponse,
  User,
  SocialUser,
  AuthState,
])
import 'package:my_circle/test/providers/enhanced_auth_provider_test.dart';
