// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:my_circle/providers/enhanced_stream_provider.dart';
import 'package:my_circle/repositories/stream_repository.dart';
import 'package:my_circle/models/stream_model.dart';
import 'package:my_circle/models/stream_chat_model.dart';

@GenerateMocks([
  StreamRepository,
  LiveStream,
  StreamChatMessage,
])
import 'package:my_circle/test/providers/enhanced_stream_provider_test.dart';
