// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:my_circle/widgets/media/enhanced_media_card.dart';
import 'package:my_circle/providers/enhanced_media_provider.dart';

@GenerateMocks([
  EnhancedMediaProvider,
  VoidCallback,
])
import 'package:my_circle/test/widgets/enhanced_media_card_test.dart';
