// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:my_circle/providers/provider_setup.dart';
import 'package:my_circle/services/supabase_service.dart';

@GenerateMocks([
  SupabaseService,
])
import 'package:my_circle/test/widgets/provider_setup_test.dart';
