// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:my_circle/repositories/auth_repository.dart';
import 'package:my_circle/services/supabase_service.dart';

@GenerateMocks([
  SupabaseService,
  SupabaseClient,
  AuthResponse,
  User,
  Session,
  AuthState,
])
import 'package:my_circle/test/repositories/auth_repository_test.dart';
