// Mocks generated by mockito
import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:my_circle/models/media_item.dart';
import 'package:my_circle/repositories/media_repository.dart';
import 'package:my_circle/services/supabase_service.dart';

@GenerateMocks([
  SupabaseService,
  SupabaseClient,
  PostgrestFilterBuilder,
  PostgrestTransformBuilder,
  User,
])
import 'package:my_circle/test/repositories/media_repository_test.dart';
