import 'package:mockito/annotations.dart';
import 'package:mycircle/providers/collection_provider.dart';
import 'package:mycircle/models/collection.dart';
import 'package:mycircle/models/media_item.dart';

// This is a mock class for CollectionProvider
// It will be generated by build_runner
class MockCollectionProvider extends Mock implements CollectionProvider {
  // State getters
  @override
  List<Collection> get myCollections => super.noSuchMethod(Invocation.method(#myCollections, [], []));
  
  @override
  List<Collection> get featuredCollections => super.noSuchMethod(Invocation.method(#featuredCollections, [], []));
  
  @override
  List<Collection> get trendingCollections => super.noSuchMethod(Invocation.method(#trendingCollections, [], []));
  
  @override
  Collection? get currentCollection => super.noSuchMethod(Invocation.method(#currentCollection, [], []));
  
  @override
  List<MediaItem> get collectionMedia => super.noSuchMethod(Invocation.method(#collectionMedia, [], []));
  
  @override
  List<Collection> get searchResults => super.noSuchMethod(Invocation.method(#searchResults, [], []));
  
  @override
  bool get isLoading => super.noSuchMethod(Invocation.method(#isLoading, [], []));
  
  @override
  bool get isLoadingCollections => super.noSuchMethod(Invocation.method(#isLoadingCollections, [], []));
  
  @override
  bool get isLoadingFeatured => super.noSuchMethod(Invocation.method(#isLoadingFeatured, [], []));
  
  @override
  bool get isLoadingTrending => super.noSuchMethod(Invocation.method(#isLoadingTrending, [], []));
  
  @override
  bool get isLoadingCurrent => super.noSuchMethod(Invocation.method(#isLoadingCurrent, [], []));
  
  @override
  bool get isLoadingMedia => super.noSuchMethod(Invocation.method(#isLoadingMedia, [], []));
  
  @override
  bool get isLoadingSearch => super.noSuchMethod(Invocation.method(#isLoadingSearch, [], []));
  
  @override
  bool get isCreating => super.noSuchMethod(Invocation.method(#isCreating, [], []));
  
  @override
  bool get isUpdating => super.noSuchMethod(Invocation.method(#isUpdating, [], []));
  
  @override
  bool get isDeleting => super.noSuchMethod(Invocation.method(#isDeleting, [], []));
  
  @override
  bool get isSearching => super.noSuchMethod(Invocation.method(#isSearching, [], []));
  
  @override
  String? get error => super.noSuchMethod(Invocation.method(#error, [], []));
  
  @override
  String? get collectionsError => super.noSuchMethod(Invocation.method(#collectionsError, [], []));
  
  @override
  String? get featuredError => super.noSuchMethod(Invocation.method(#featuredError, [], []));
  
  @override
  String? get trendingError => super.noSuchMethod(Invocation.method(#trendingError, [], []));
  
  @override
  String? get currentError => super.noSuchMethod(Invocation.method(#currentError, [], []));
  
  @override
  String? get mediaError => super.noSuchMethod(Invocation.method(#mediaError, [], []));
  
  @override
  String? get searchError => super.noSuchMethod(Invocation.method(#searchError, [], []));
  
  @override
  String get searchQuery => super.noSuchMethod(Invocation.method(#searchQuery, [], []));
  
  @override
  bool get hasMoreCollections => super.noSuchMethod(Invocation.method(#hasMoreCollections, [], []));
  
  @override
  bool get hasMoreMedia => super.noSuchMethod(Invocation.method(#hasMoreMedia, [], []));
  
  @override
  bool get hasMoreSearch => super.noSuchMethod(Invocation.method(#hasMoreSearch, [], []));
}
