import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// This is a mock class for SupabaseClient
// It will be generated by build_runner
class MockSupabaseClient extends Mock implements SupabaseClient {
  @override
  PostgrestFilterBuilder from(String tableName) {
    return super.noSuchMethod(Invocation.method(#from, [tableName], {}));
  }
}

// Mock for PostgrestFilterBuilder
class MockPostgrestFilterBuilder extends Mock implements PostgrestFilterBuilder {
  @override
  PostgrestFilterBuilder select(List<String> columns) {
    return super.noSuchMethod(Invocation.method(#select, [columns], {}));
  }

  @override
  PostgrestFilterBuilder eq(String column, dynamic value) {
    return super.noSuchMethod(Invocation.method(#eq, [column, value], {}));
  }

  @override
  PostgrestFilterBuilder order(String column, {bool ascending = false}) {
    return super.noSuchMethod(Invocation.method(#order, [column], {#ascending: ascending}));
  }

  @override
  PostgrestFilterBuilder range(int from, int to) {
    return super.noSuchMethod(Invocation.method(#range, [from, to], {}));
  }

  @override
  PostgrestFilterBuilder limit(int limit) {
    return super.noSuchMethod(Invocation.method(#limit, [limit], {}));
  }

  @override
  PostgrestFilterBuilder or(String filter) {
    return super.noSuchMethod(Invocation.method(#or, [filter], {}));
  }

  @override
  PostgrestFilterBuilder insert(Map<String, dynamic> data) {
    return super.noSuchMethod(Invocation.method(#insert, [data], {}));
  }

  @override
  PostgrestFilterBuilder update(Map<String, dynamic> data) {
    return super.noSuchMethod(Invocation.method(#update, [data], {}));
  }

  @override
  PostgrestFilterBuilder delete() {
    return super.noSuchMethod(Invocation.method(#delete, [], {}));
  }

  @override
  Future<PostgrestResponse> single() {
    return super.noSuchMethod(Invocation.method(#single, [], {}));
  }

  @override
  Future<PostgrestResponse> then(Future<PostgrestResponse> Function(PostgrestResponse) onValue) {
    return super.noSuchMethod(Invocation.method(#then, [onValue], {}));
  }

  @override
  PostgrestFilterBuilder onConflict(String conflictAction) {
    return super.noSuchMethod(Invocation.method(#onConflict, [conflictAction], {}));
  }
}

// Mock for PostgrestResponse
class MockPostgrestResponse extends Mock implements PostgrestResponse {
  @override
  dynamic get data => super.noSuchMethod(Invocation.getter(#data), {});
}
